"""add cefr_level to grammar_rules and learner_profiles table

Revision ID: 3508ca854385
Revises: 50e9d658c6b3
Create Date: 2026-04-04 09:23:37.936619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3508ca854385'
down_revision: Union[str, Sequence[str], None] = '50e9d658c6b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learner_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=False),
    sa.Column('streak_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('xp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cefr_estimate', sa.String(length=3), server_default='B1', nullable=False),
    sa.Column('weak_topics', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_profiles_telegram_chat_id'), 'learner_profiles', ['telegram_chat_id'], unique=True)
    op.add_column('grammar_rules', sa.Column('cefr_level', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grammar_rules', 'cefr_level')
    op.drop_index(op.f('ix_learner_profiles_telegram_chat_id'), table_name='learner_profiles')
    op.drop_table('learner_profiles')
    # ### end Alembic commands ###
