"""add telegram and langfuse fields to assignment_submissions

Revision ID: 50e9d658c6b3
Revises: cb0f58a77768
Create Date: 2026-04-03 14:39:19.851815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50e9d658c6b3'
down_revision: Union[str, Sequence[str], None] = 'cb0f58a77768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_submissions', sa.Column('telegram_message_id', sa.String(), nullable=True))
    op.add_column('assignment_submissions', sa.Column('langfuse_trace_id', sa.String(), nullable=True))
    op.add_column('assignment_submissions', sa.Column('flagged_for_review', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('assignment_submissions', sa.Column('flagged_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment_submissions', 'flagged_at')
    op.drop_column('assignment_submissions', 'flagged_for_review')
    op.drop_column('assignment_submissions', 'langfuse_trace_id')
    op.drop_column('assignment_submissions', 'telegram_message_id')
    # ### end Alembic commands ###
