"""add telegram_chat_id to assignments

Revision ID: e4ebd9b6826a
Revises: 3508ca854385
Create Date: 2026-04-04 10:39:12.174278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ebd9b6826a'
down_revision: Union[str, Sequence[str], None] = '3508ca854385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('telegram_chat_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_assignments_telegram_chat_id'), 'assignments', ['telegram_chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignments_telegram_chat_id'), table_name='assignments')
    op.drop_column('assignments', 'telegram_chat_id')
    # ### end Alembic commands ###
