"""add processed_images table

Revision ID: f66783a4429f
Revises: 8dcdb251fb14
Create Date: 2026-03-26 19:41:55.264698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66783a4429f'
down_revision: Union[str, Sequence[str], None] = '8dcdb251fb14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_unique_id', sa.String(length=64), nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_images_file_unique_id'), 'processed_images', ['file_unique_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_images_file_unique_id'), table_name='processed_images')
    op.drop_table('processed_images')
    # ### end Alembic commands ###
